config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  d_spacevim.d:
    src: SpaceVim.d
    dst: ~/.SpaceVim.d
  d_i3:
    src: i3
    dst: ~/.i3
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_i3status_config:
    src: config/i3status/config
    dst: ~/.config/i3status/config
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  d_spacemacs.d:
    src: spacemacs.d
    dst: ~/.spacemacs.d
  d_conky:
    src: xmonad/conky
    dst: ~/.xmonad/conky
  f_xmonad.hs:
    src: xmonad/xmonad.hs
    dst: ~/.xmonad/xmonad.hs
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_zsh:
    src: zsh
    dst: ~/.zsh
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_st:
    src: bin/st
    dst: ~/bin/st
  d_dwm:
    src: bin/dwm
    dst: ~/bin/dwm
  d_dwm_1:
    src: dwm
    dst: ~/.dwm
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  d_doom.d:
    src: doom.d
    dst: ~/.doom.d
  f_mk-desktop:
    src: bin/mk-desktop
    dst: ~/bin/mk-desktop
    chmod: '755'
  d_rime:
    src: local/share/fcitx5/rime
    dst: ~/.local/share/fcitx5/rime
profiles:
  mslxl-PC:
    dotfiles:
    - f_xprofile
    - f_xresources
    - f_picom.conf
    - f_zshrc
    - d_zsh
    - f_gitconfig
    - d_st
    - d_dwm
    - d_dwm_1
    - f_tmux.conf
    - d_doom.d
    - f_mk-desktop
    - d_rime
  disable:
    dotfiles:
    - f_xmonad.hs
    - d_conky
    - d_spacemacs.d
    - d_spacevim.d
    - f_i3status_config
    - d_i3
    - f_alacritty.yml
    - d_alacritty
