name: xmonad-config
version: 0.1.0
synopsis: xmonad setting
github: mslxl/.dotfiles
author: mslxl
maintainer: i@mslxl.com
license: AGPL
dependencies:
  - X11
  - base
  - xmonad
  - xmonad-contrib
  - containers
  - directory
  - filepath
executables:
  xmonad:
    main: xmonad.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
